### ISSUE TITLE
com.aliyun.odps.mapred.JobClient submitJob 找不到

### ISSUE THREAD

**Issue by Anson2048** [aliyun/aliyun-odps-java-sdk#1]
我参照 [何在本地调用odps服务器运行mapreduce任务](https://help.aliyun.com/knowledge_detail/7612181.html?spm=5176.789025842.2.2.VUrbm8#如何在本地调用odps服务器运行mapreduce任务)  错误如下：
Mar 29, 2016 2:22:54 PM com.aliyun.odps.mapred.JobClient submitJob
SEVERE: Internal error: corrupted installation.
java.lang.ClassNotFoundException: com.aliyun.odps.mapred.LotBridgeJobRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.aliyun.odps.mapred.JobClient.submitJob(JobClient.java:176)
	at com.aliyun.odps.mapred.JobClient.submitJob(JobClient.java:153)
	at com.aliyun.odps.mapred.Job.submit(Job.java:134)
	at com.augmentum.test.odps.WordCount.WordCount.main(WordCount.java:138)

Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: com.aliyun.odps.mapred.LotBridgeJobRunner
	at com.aliyun.odps.mapred.JobClient.submitJob(JobClient.java:180)
	at com.aliyun.odps.mapred.JobClient.submitJob(JobClient.java:153)
	at com.aliyun.odps.mapred.Job.submit(Job.java:134)
	at com.augmentum.test.odps.WordCount.WordCount.main(WordCount.java:138)
Caused by: java.lang.ClassNotFoundException: com.aliyun.odps.mapred.LotBridgeJobRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.aliyun.odps.mapred.JobClient.submitJob(JobClient.java:176)
	... 3 more

-----

我应该如何调用服务端的 `job`

**Comment by onesuper** [comment]
在 sdk 中提交 MR job 需要有 bridge 这个 jar，但是对外没有发布

**Comment by onesuper** [comment]
可以用 odpscmd 来提交

**Comment by Anson2048** [comment]
谢谢

**Comment by linuful** [comment]
LotBridgeJobRunner 麻烦问下现在这个类会提供吗？

**Comment by lyman** [comment]
已经提供了啊

https://github.com/aliyun/aliyun-odps-java-sdk/blob/master/odps-sdk-impl/odps-mapred-bridge/src/main/java/com/aliyun/odps/mapred/LotBridgeJobRunner.java
